AUGMENTATION: True 
IMAGE_SIZE: [224, 224, 3] 
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 2
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.08
USE_CLASS_WEIGHTS: true
USE_LR_SCHEDULER: true
EARLY_STOPPING_PATIENCE: 10
DROPOUT_RATE: 0.5
LABEL_FORMAT: "categorical"

EFFICIENTNETB2:
  IMAGE_SIZE: [288, 288, 3]              
  BATCH_SIZE: 32
  EPOCHS: 2                             
  LEARNING_RATE: 0.0001
  USE_CLASS_WEIGHTS: true
  USE_LR_SCHEDULER: true
  EARLY_STOPPING_PATIENCE: 5
  DROPOUT_RATE: 0.3
  LABEL_FORMAT: "sparse"